@DotNetLearningPlatform.Api_HostAddress = http://localhost:5041

POST {{DotNetLearningPlatform.Api_HostAddress}}/api/code/execute
Content-Type: application/json

{
  "sourceCode": "Console.WriteLine(\"Hello from the API\");",
  "language": "csharp"
}
